---
title: "covid19_mfuzz"
author: "liuwe"
date: "2020年3月26日"
output: html_document
---
```{r mfuzz-proteomics}
rm(list = ls())
library(readr)
library(plyr)
library(readxl)
library(stringr)
library(magrittr)
library(Mfuzz)
source("datamining_library_ge20200306.R")

info <- read_xlsx("sampleinfo2.xlsx")
info$TMT <- gsub("^b","F",info$TMT)

 ################d

df2<-read.table("proteomic_matrix_ratio20200328.txt",header = T,sep = "\t",row.names = 1)

df3<-data.frame(names(df2),t(df2))

names(df3)<-c("TMT",as.matrix(names(df3[,-1])))


df4<-merge(info,df3,by.x = "TMT")



df5<-df4[-c(which(df4$Type=="NA")),-1]




df6<-aggregate(df5[,colnames(df5)[2:ncol(df5)]],by=list(df5$Type),mean,na.rm= TRUE)

df6<-df6[c(1,2,3,4),]

row.names(df6)<-c(as.matrix((df6[,1])))


df7<-data.frame(t(df6[,-1]))

df7<-data.frame(df7[,c(1,2,3,4)])

##################

set.seed(2021)

a<-ge.mfuzz.cselection(df7,range = seq(3,10,1))

b<-ge.mfuzz.getresult(a,8,"4_protein_mfuzz_ge2021type_8")




```

```{r anova-proteomics}
rm(list = ls())
library(readr)
library(plyr)
library(readxl)
library(stringr)
library(magrittr)
source("datamining_library_ge20200306.R")

info <- read_xlsx("sampleinfo2.xlsx")
info$TMT <- gsub("^b","F",info$TMT)

df2<-read.table("proteomic_matrix_ratio20200328.txt",header = T,sep = "\t",row.names = 1)
df3<-data.frame(names(df2),t(df2))

names(df3)<-c("TMT",as.matrix(names(df3[,-1])))


df4<-merge(info,df3,by.x = "TMT")



df5<-df4[-c(which(df4$Type=="NA")),-1]


############################################

Matrix<-df5

for (K in 1:8) {
  


mfuzz_prot<-read.csv(paste0("4_protein_mfuzz_ge2021type_8/mfuzz_",K,".csv"))

prot<-as.matrix(mfuzz_prot$X)

Matrix2<-data.frame(Matrix[,1],Matrix[,c(which(names(Matrix)%in% prot))])




col<-ncol(Matrix2)
names(Matrix2)<-c("label",as.matrix(names(Matrix2[,-1])))
anova<-data.frame(names(Matrix2[,-1]))


for (i in 2:col) {
  aov<-(summary(aov(Matrix2[,i] ~ Matrix2[,1],Matrix2))[[1]])$`Pr(>F)`[1]
  aov<-as.numeric(aov)
  # aov<-as.numeric(aov,digits = 4, scientific = F)
  anova[c(i-1),2]<-aov
}

names(anova)<-c('protein',"pvalue")

anova2<-data.frame(anova[c(which(anova$pvalue<=0.05)),])


write.csv(anova2,paste0("4_protein_mfuzz_ge2021type_8/",K,"_mfuzz_anova_0.05.csv"),row.names = F)



}

```



```{r mfuzz-metabo}

rm(list = ls())
library(readr)
library(plyr)
library(readxl)
library(stringr)
library(magrittr)
source("datamining_library_ge20200306.R")
library(RColorBrewer)
library(pheatmap)
library(Mfuzz)

matrix<-read.csv("meta/meta_matrix_log2delectNA08anddrug36_NAmin20200329(1).csv")

row.names(matrix)<-c(as.matrix(matrix[,1]))




info<-read_excel("meta/sTable1_20200329-1900.xlsx",sheet = 2)


info2<-info[,c(8,14,15)]




names(info2)<-c("type","sex","age")


matrix2<-data.frame(names(matrix[,-1]),t(matrix[,-1]))



names(matrix2)<-c("type",c(as.matrix(matrix[,1])))


matrix3<-merge(info2,matrix2,by.x = "type")

matrix5<-data.frame(c(as.matrix(matrix3[,1])),matrix3)





matrix5$type<-gsub("\\d+","",perl = T,matrix5$type)


matrix5$sex<-gsub("1","M",perl = T,matrix5$sex)

matrix5$sex<-gsub("0","F",perl = T,matrix5$sex)





df5<-data.frame(matrix5[,-c(1,3,4)])



df6<-aggregate(df5[,colnames(df5)[2:ncol(df5)]],by=list(df5$type),mean,na.rm= TRUE)



row.names(df6)<-c(as.matrix(df6$Group.1))


df7.1<-data.frame(t(df6[,-1]))

df7<-data.frame(df7.1[,c(1,3,4)])


row.names(df7)<-row.names(matrix)

##################

set.seed(2021)

a<-ge.mfuzz.cselection(df7,range = seq(3,10,1))

b<-ge.mfuzz.getresult(a,8,"meta/mfuzz_ge2021type_8_meta_new")




```

```{r anova-metabo}
rm(list = ls())
library(readr)
library(plyr)
library(readxl)
library(stringr)
library(magrittr)
library(Mfuzz)
source("datamining_library_ge20200306.R")
rm(list = ls())
library(readr)
library(plyr)
library(readxl)
library(stringr)
library(magrittr)
source("datamining_library_ge20200306.R")
library(RColorBrewer)
library(pheatmap)


matrix<-read.csv("meta/meta_matrix_log2delectNA08anddrug36_NAmin20200329(1).csv")

row.names(matrix)<-c(as.matrix(matrix[,1]))




info<-read_excel("meta/sTable1_20200329-1900.xlsx",sheet = 2)


info2<-info[,c(8,14,15)]




names(info2)<-c("type","sex","age")


matrix2<-data.frame(names(matrix[,-1]),t(matrix[,-1]))



names(matrix2)<-c("type",c(as.matrix(matrix[,1])))






matrix3<-merge(info2,matrix2,by.x = "type")

matrix5<-data.frame(c(as.matrix(matrix3[,1])),matrix3)





matrix5$type<-gsub("\\d+","",perl = T,matrix5$type)


matrix5$sex<-gsub("1","M",perl = T,matrix5$sex)

matrix5$sex<-gsub("0","F",perl = T,matrix5$sex)





df5<-data.frame(matrix5[,-c(1,3,4)])







############################################

df6<-data.frame(df5[-c(which(df5$type=="jbdz")),])

Matrix<-df6




for (K in 1:8) {
  
mfuzz_prot<-read.csv(paste0("meta/mfuzz_ge2021type_8_meta_new/mfuzz_",K,".csv"))


row.names(mfuzz_prot)<-c(as.matrix(mfuzz_prot[,1]))


mfuzz_prot2<-data.frame(t(mfuzz_prot))

prot<-as.matrix(names(mfuzz_prot2))







Matrix2<-data.frame(Matrix[,1],Matrix[,c(which(names(Matrix)%in% prot))])


col<-ncol(Matrix2)
names(Matrix2)<-c("label",as.matrix(names(Matrix2[,-1])))
anova<-data.frame(names(Matrix2[,-1]))


for (i in 2:col) {
  aov<-(summary(aov(Matrix2[,i] ~ Matrix2[,1],Matrix2))[[1]])$`Pr(>F)`[1]
  aov<-as.numeric(aov)
  # aov<-as.numeric(aov,digits = 4, scientific = F)
  anova[c(i-1),2]<-aov
}

names(anova)<-c('protein',"pvalue")

anova2<-data.frame(anova[c(which(anova$pvalue<=0.05)),])


write.csv(anova2,paste0("meta/mfuzz_ge2021type_8_meta_new/",K,"_mfuzz_anova_0.05.csv"),row.names = F)


}



```














