---
title: "CVDSBA"
author: "Weigang Ge"
date: "2020/3/28"
output: html_document
---

generate matrix
```{r}
rm(list = ls())
library(readr)
library(plyr)
library(readxl)
library(stringr)
library(magrittr)
source("D:/datamining_library_ge20200306.R")
df <- read_xls("Taizhou20200328.xls",col_names = T)
df1 <- df[-c(1:2),-1] %>% as.data.frame()
row.names(df1) <- df$...1[-c(1:2)]
names(df1) <- df[1,-1]
label <- gsub("\\d+","",names(df1))

df2 <- apply(df1,1, as.numeric) %>% t() %>% as.data.frame() %>% log2()
names(df2) <- names(df1)

ge.na.ratio(df2)
ge.plot.density( df2)
max(df2,na.rm = T)
min(df2,na.rm = T)


#delect 36 drugs 
detect <- read_xlsx("Detected Drugs information from Calibra.xlsx",col_names = F)
df2 <- df2[-which(row.names(df2) %in% detect$...1),]

```




VOLCANO ZX - PT (in other words: severe - nonsevere)
```{r}

library(RColorBrewer)
zx_type <- which(label=="ZX")
pt_type <- which(label=="PT")


# delect NA ratio > 0.8 
df7 <- df2[!apply(df2, 1, function(x)(sum(is.na(x[zx_type]))/length(zx_type) > 0.8) | sum(is.na(x[pt_type]))/length(pt_type) > 0.8),]


# NA is assigned to the minimum value
for (i in 1:nrow(df7)) {
  df7[i,][is.na(df7[i,])] <- min(df7[i,],na.rm = T)
}


# foldchange
df8 <- 2^df7
df8$fd <- apply(df8,1, function(x) log2((mean(x[zx_type],na.rm = T)/mean(x[pt_type],na.rm = T))))
x<-c(0.0,0.0)
df9 <- df7


# pvalue and adjust
for(i in 1:nrow(df9)){
    x[i] <- t.test(df9[i,zx_type],df9[i,pt_type], paired = F, var.equal = F)$p.value
}
df8$P_value<-x
df8$P_value_adjust<-p.adjust(df8$P_value, method="BH")

pdf("ZX_PT_labelpoint.pdf")
df.point <- data.frame(mean=apply(df7[,c(zx_type,pt_type)],1,mean),fc=df8$fd)
up <- subset(df.point, df.point$mean >23 & df.point$fc > 0.25)
down <- subset(df.point, df.point$mean <16 & df.point$fc < -0.25)
write.csv(rbind(up,down),file = "ZX_PT_point.csv")
plot(df.point$mean,df.point$fc)
abline(h=c(-0.25,0.25),lty=2,lwd=1)
  text(up$mean, up$fc,row.names(up),cex=0.5)
  text(down$mean, down$fc,row.names(down),cex=0.5)
dev.off()
pdf("ZX_PT_point.pdf")
df.point <- data.frame(mean=apply(df7[,c(zx_type,pt_type)],1,mean),fc=df8$fd)
plot(df.point$mean,df.point$fc)
abline(h=c(-0.25,0.25),lty=2,lwd=1)
dev.off()


# volcano plot 
pdf("ZX_PT_volcano.pdf")
plot(df8$fd, -log10(df8$P_value_adjust), col="#00000033", pch=19,
      xlab=paste("log2 (fold change)"),
      ylab="-log10 (P_value_adjust)",xlim=c(-4,4),
      main="ZX & PT")

up <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd > 0.25)
down <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd < -0.25)
write.csv(up,file = "ZX_PT_up_volcano.csv")
write.csv(down,file = "ZX_PT_dw_volcano.csv")
points(up$fd, -log10(up$P_value_adjust), col=1, bg = brewer.pal(9, "YlOrRd")[6], pch=21, cex=1.5)
points(down$fd, -log10(down$P_value_adjust), col = 1, bg = brewer.pal(11,"RdBu")[9], pch = 21,cex=1.5)
abline(h=1.3, v=c(-0.25,0.25), lty=2,lwd=1)
dev.off()

# volcano plot with label 
pdf("ZX_PT_labelvolcano.pdf")
plot(df8$fd, -log10(df8$P_value_adjust), col="#00000033", pch=19,
      xlab=paste("log2 (fold change)"),
      ylab="-log10 (P_value_adjust)",xlim=c(-4,4),
      main="ZX & PT")

up <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd > 0.25)
down <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd < -0.25)
points(up$fd, -log10(up$P_value_adjust), col=1, bg = brewer.pal(9, "YlOrRd")[6], pch=21, cex=1.5)
points(down$fd, -log10(down$P_value_adjust), col = 1, bg = brewer.pal(11,"RdBu")[9], pch = 21,cex=1.5)
text(up$fd, -log10(up$P_value_adjust),row.names(up),cex=0.5)
text(down$fd, -log10(down$P_value_adjust),row.names(down),cex=0.5)
abline(h=1.3, v=c(-0.25,0.25), lty=2,lwd=1)
dev.off()
```


VOLCANO jbdz/ jkdz (in other words: nonCOVID19 - healthy)
```{r}
library(RColorBrewer)
jbdz_type <- which(label=="jbdz")
jkbz_type <- which(label=="jkdz")

df7 <- df2[!apply(df2, 1, function(x)(sum(is.na(x[jbdz_type]))/length(jbdz_type) > 0.8) | sum(is.na(x[jkbz_type]))/length(jkbz_type) > 0.8),]

for (i in 1:nrow(df7)) {
  df7[i,][is.na(df7[i,])] <- min(df7[i,],na.rm = T)
}

df8 <- 2^df7
df8$fd <- apply(df8,1, function(x) log2((mean(x[jbdz_type],na.rm = T)/mean(x[jkbz_type],na.rm = T))))
x<-c(0.0,0.0)
df9 <- df7

for(i in 1:nrow(df9)){
    x[i] <- t.test(df9[i,jbdz_type],df9[i,jkbz_type], paired = F, var.equal = F)$p.value
}
df8$P_value<-x
df8$P_value_adjust<-p.adjust(df8$P_value, method="BH")


pdf("jbdz_jkdz_labelpoint.pdf")
df.point <- data.frame(mean=apply(df7[,c(jbdz_type,jkbz_type)],1,mean),fc=df8$fd)
up <- subset(df.point, df.point$mean >23 & df.point$fc > 0.25)
down <- subset(df.point, df.point$mean <16 & df.point$fc < -0.25)
write.csv(rbind(up,down),file = "jbdz_jkdz_point.csv")
plot(df.point$mean,df.point$fc)
abline(h=c(-0.25,0.25),lty=2,lwd=1)
  text(up$mean, up$fc,row.names(up),cex=0.5)
  text(down$mean, down$fc,row.names(down),cex=0.5)
dev.off()
pdf("jbdz_jkdz_point.pdf")
df.point <- data.frame(mean=apply(df7[,c(jbdz_type,jkbz_type)],1,mean),fc=df8$fd)
plot(df.point$mean,df.point$fc)
abline(h=c(-0.25,0.25),lty=2,lwd=1)
dev.off()

pdf("jbdz_jkdz_volcano.pdf")
plot(df8$fd, -log10(df8$P_value_adjust), col="#00000033", pch=19,
      xlab=paste("log2 (fold change)"),
      ylab="-log10 (P_value_adjust)",xlim=c(-4,4),
      main="jbdz / jkdz")

up <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd > 0.25)
down <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd < -0.25)
write.csv(up,file = "jbdz_jkdz_up_volcano.csv")
write.csv(down,file = "jbdz_jkdz_dw_volcano.csv")
points(up$fd, -log10(up$P_value_adjust), col=1, bg = brewer.pal(9, "YlOrRd")[6], pch=21, cex=1.5)
points(down$fd, -log10(down$P_value_adjust), col = 1, bg = brewer.pal(11,"RdBu")[9], pch = 21,cex=1.5)
abline(h=1.3,v=c(-0.25,0.25),lty=2,lwd=1)
dev.off()



pdf("jbdz_jkdz_labelvolcano.pdf")
plot(df8$fd, -log10(df8$P_value_adjust), col="#00000033", pch=19,
      xlab=paste("log2 (fold change)"),
      ylab="-log10 (P_value_adjust)",xlim=c(-4,4),
      main="jbdz / jkdz")

up <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd > 0.25)
down <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd < -0.25)
points(up$fd, -log10(up$P_value_adjust), col=1, bg = brewer.pal(9, "YlOrRd")[6], pch=21, cex=1.5)
points(down$fd, -log10(down$P_value_adjust), col = 1, bg = brewer.pal(11,"RdBu")[9], pch = 21,cex=1.5)
text(up$fd, -log10(up$P_value_adjust),row.names(up),cex=0.5)
text(down$fd, -log10(down$P_value_adjust),row.names(down),cex=0.5)
abline(h=1.3,v=c(-0.25,0.25),lty=2,lwd=1)
dev.off()
```


VOLCANO PT/ jkdz (in other words: nonsevere - healthy)
```{r}
library(RColorBrewer)
PT_type <- which(label=="PT")
jkbz_type <- which(label=="jkdz")


df7 <- df2[!apply(df2, 1, function(x)(sum(is.na(x[PT_type]))/length(PT_type) > 0.8) | sum(is.na(x[jkbz_type]))/length(jkbz_type) > 0.8),]

for (i in 1:nrow(df7)) {
  df7[i,][is.na(df7[i,])] <- min(df7[i,],na.rm = T)
}

df8 <- 2^df7
df8$fd <- apply(df8,1, function(x) log2((mean(x[PT_type],na.rm = T)/mean(x[jkbz_type],na.rm = T))))
x<-c(0.0,0.0)
df9 <- df7

for(i in 1:nrow(df9)){
    x[i] <- t.test(df9[i,PT_type],df9[i,jkbz_type], paired = F, var.equal = F)$p.value
}
df8$P_value<-x
df8$P_value_adjust<-p.adjust(df8$P_value, method="BH")

pdf("PT_jkdz_labelpoint.pdf")
df.point <- data.frame(mean=apply(df7[,c(PT_type,jkbz_type)],1,mean),fc=df8$fd)
up <- subset(df.point, df.point$mean >23 & df.point$fc > 0.25)
down <- subset(df.point, df.point$mean <16 & df.point$fc < -0.25)
write.csv(rbind(up,down),file = "PT_jkdz_point.csv")
plot(df.point$mean,df.point$fc)
abline(h=c(-0.25,0.25),lty=2,lwd=1)
  text(up$mean, up$fc,row.names(up),cex=0.5)
  text(down$mean, down$fc,row.names(down),cex=0.5)
dev.off()
pdf("PT_jkdz_point.pdf")
df.point <- data.frame(mean=apply(df7[,c(PT_type,jkbz_type)],1,mean),fc=df8$fd)
plot(df.point$mean,df.point$fc)
abline(h=c(-0.25,0.25),lty=2,lwd=1)
dev.off()

pdf("PT_jkdz_volcano.pdf")
plot(df8$fd, -log10(df8$P_value_adjust), col="#00000033", pch=19,
      xlab=paste("log2 (fold change)"),
      ylab="-log10 (P_value)",xlim=c(-4,4),
      main="PT / jkdz")

up <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd > 0.25)
down <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd < -0.25)
write.csv(up,file = "PT_jkdz_up_volcano.csv")
write.csv(down,file = "PT_jkdz_dw_volcano.csv")
points(up$fd, -log10(up$P_value_adjust), col=1, bg = brewer.pal(9, "YlOrRd")[6], pch=21, cex=1.5)
points(down$fd, -log10(down$P_value_adjust), col = 1, bg = brewer.pal(11,"RdBu")[9], pch = 21,cex=1.5)
abline(h=1.3,v=c(-0.25,0.25),lty=2,lwd=1)
dev.off()
  
  pdf("PT_jkdz_labelvolcano.pdf")
  plot(df8$fd, -log10(df8$P_value_adjust), col="#00000033", pch=19,
        xlab=paste("log2 (fold change)"),
        ylab="-log10 (P_value)",xlim=c(-4,4),
        main="PT / jkdz")
  
  up <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd > 0.25)
  down <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd < -0.25)
  points(up$fd, -log10(up$P_value_adjust), col=1, bg = brewer.pal(9, "YlOrRd")[6], pch=21, cex=1.5)
  points(down$fd, -log10(down$P_value_adjust), col = 1, bg = brewer.pal(11,"RdBu")[9], pch = 21,cex=1.5)
  text(up$fd, -log10(up$P_value_adjust),row.names(up),cex=0.5)
  text(down$fd, -log10(down$P_value_adjust),row.names(down),cex=0.5)
  abline(h=1.3,v=c(-0.25,0.25),lty=2,lwd=1)
  dev.off()

  
# tmp1 <- df7[,PT_type]
# tmp2 <- df7[,jkbz_type]

# 
# vioplot(as.numeric(as.matrix(tmp1)) ,as.numeric(as.matrix(tmp2) ) ,
#          areaEqual=FALSE,
#         # rectCol= color, col= color,
#         lineCol=c("black", "black"),
#         border=c("black","black"),
#         names=c("PT_type","jkbz_type"),
#         main="biological replicates", plotCentre = "point")

```


VOLCANO PT/ jbdz (in other words: nonsevere - nonCOVID19)
```{r}
library(RColorBrewer)
PT_type <- which(label=="PT")
jkbz_type <- which(label=="jkdz")
jbdz_type <- which(label=="jbdz")

df7 <- df2[!apply(df2, 1, function(x)(sum(is.na(x[PT_type]))/length(PT_type) > 0.8) | sum(is.na(x[jbdz_type]))/length(jbdz_type) > 0.8),]

for (i in 1:nrow(df7)) {
  df7[i,][is.na(df7[i,])] <- min(df7[i,],na.rm = T)
}

df8 <- 2^df7
df8$fd <- apply(df8,1, function(x) log2((mean(x[PT_type],na.rm = T)/mean(x[jbdz_type],na.rm = T))))
x<-c(0.0,0.0)
df9 <- df7

for(i in 1:nrow(df9)){
    x[i] <- t.test(df9[i,PT_type],df9[i,jbdz_type], paired = F, var.equal = F)$p.value
}
df8$P_value<-x
df8$P_value_adjust<-p.adjust(df8$P_value, method="BH")

pdf("PT_jbdz_labelpoint.pdf")
df.point <- data.frame(mean=apply(df7[,c(PT_type,jbdz_type)],1,mean),fc=df8$fd)
up <- subset(df.point, df.point$mean >23 & df.point$fc > 0.25)
down <- subset(df.point, df.point$mean <16 & df.point$fc < -0.25)
write.csv(rbind(up,down),file = "PT_jbdz_point.csv")
plot(df.point$mean,df.point$fc)
abline(h=c(-0.25,0.25),lty=2,lwd=1)
  text(up$mean, up$fc,row.names(up),cex=0.5)
  text(down$mean, down$fc,row.names(down),cex=0.5)
dev.off()
pdf("PT_jbdz_point.pdf")
df.point <- data.frame(mean=apply(df7[,c(PT_type,jbdz_type)],1,mean),fc=df8$fd)
plot(df.point$mean,df.point$fc)
abline(h=c(-0.25,0.25),lty=2,lwd=1)
dev.off()

pdf("PT_jbdz_volcano.pdf")
plot(df8$fd, -log10(df8$P_value_adjust), col="#00000033", pch=19,
      xlab=paste("log2 (fold change)"),
      ylab="-log10 (P_value)",xlim=c(-4,4),
      main="PT / jbdz")

up <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd > 0.25)
down <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd < -0.25)
write.csv(up,file = "PT_jbdz_up_volcano.csv")
write.csv(down,file = "PT_jbdz_dw_volcano.csv")
points(up$fd, -log10(up$P_value_adjust), col=1, bg = brewer.pal(9, "YlOrRd")[6], pch=21, cex=1.5)
points(down$fd, -log10(down$P_value_adjust), col = 1, bg = brewer.pal(11,"RdBu")[9], pch = 21,cex=1.5)
abline(h=1.3,v=c(-0.25,0.25),lty=2,lwd=1)
dev.off()

pdf("PT_jbdz_labelvolcano.pdf")
plot(df8$fd, -log10(df8$P_value_adjust), col="#00000033", pch=19,
      xlab=paste("log2 (fold change)"),
      ylab="-log10 (P_value)",xlim=c(-4,4),
      main="PT / jbdz")

up <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd > 0.25)
down <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd < -0.25)
points(up$fd, -log10(up$P_value_adjust), col=1, bg = brewer.pal(9, "YlOrRd")[6], pch=21, cex=1.5)
points(down$fd, -log10(down$P_value_adjust), col = 1, bg = brewer.pal(11,"RdBu")[9], pch = 21,cex=1.5)
  text(up$fd, -log10(up$P_value_adjust),row.names(up),cex=0.5)
  text(down$fd, -log10(down$P_value_adjust),row.names(down),cex=0.5)
abline(h=1.3,v=c(-0.25,0.25),lty=2,lwd=1)
dev.off()
```


VOLCANO zx/ jkdz (in other words: severe - healthy)
```{r}
library(RColorBrewer)
PT_type <- which(label=="PT")
ZX_type <- which(label=="ZX")
jkdz_type <- which(label=="jkdz")
jbdz_type <- which(label=="jbdz")

df7 <- df2[!apply(df2, 1, function(x)(sum(is.na(x[ZX_type]))/length(ZX_type) > 0.8) | sum(is.na(x[jkdz_type]))/length(jkdz_type) > 0.8),]

for (i in 1:nrow(df7)) {
  df7[i,][is.na(df7[i,])] <- min(df7[i,],na.rm = T)
}

df8 <- 2^df7
df8$fd <- apply(df8,1, function(x) log2((mean(x[ZX_type],na.rm = T)/mean(x[jkdz_type],na.rm = T))))
x<-c(0.0,0.0)
df9 <- df7

for(i in 1:nrow(df9)){
    x[i] <- t.test(df9[i,ZX_type],df9[i,jkdz_type], paired = F, var.equal = F)$p.value
}
df8$P_value<-x
df8$P_value_adjust<-p.adjust(df8$P_value, method="BH")

pdf("ZX_jkdz_labelpoint.pdf")
df.point <- data.frame(mean=apply(df7[,c(ZX_type,jkdz_type)],1,mean),fc=df8$fd)
up <- subset(df.point, df.point$mean >23 & df.point$fc > 0.25)
down <- subset(df.point, df.point$mean <16 & df.point$fc < -0.25)
write.csv(rbind(up,down),file = "ZX_jkdz_point.csv")
plot(df.point$mean,df.point$fc)
abline(h=c(-0.25,0.25),lty=2,lwd=1)
  text(up$mean, up$fc,row.names(up),cex=0.5)
  text(down$mean, down$fc,row.names(down),cex=0.5)
dev.off()
pdf("ZX_jkdz_point.pdf")
df.point <- data.frame(mean=apply(df7[,c(ZX_type,jkdz_type)],1,mean),fc=df8$fd)
plot(df.point$mean,df.point$fc)
abline(h=c(-0.25,0.25),lty=2,lwd=1)
dev.off()


pdf("ZX_jkdz_volcano.pdf")
plot(df8$fd, -log10(df8$P_value_adjust), col="#00000033", pch=19,
      xlab=paste("log2 (fold change)"),
      ylab="-log10 (P_value)",xlim=c(-4,4),
      main="ZX / jkdz")

up <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd > 0.25)
down <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd < -0.25)
write.csv(up,file = "ZX_jkdz_up_volcano.csv")
write.csv(down,file = "ZX_jkdz_dw_volcano.csv")
points(up$fd, -log10(up$P_value_adjust), col=1, bg = brewer.pal(9, "YlOrRd")[6], pch=21, cex=1.5)
points(down$fd, -log10(down$P_value_adjust), col = 1, bg = brewer.pal(11,"RdBu")[9], pch = 21,cex=1.5)
abline(h=1.3,v=c(-0.25,0.25),lty=2,lwd=1)
dev.off()

pdf("ZX_jkdz_labelvolcano.pdf")
plot(df8$fd, -log10(df8$P_value_adjust), col="#00000033", pch=19,
      xlab=paste("log2 (fold change)"),
      ylab="-log10 (P_value)",xlim=c(-4,4),
      main="ZX / jkdz")

up <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd > 0.25)
down <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd < -0.25)
points(up$fd, -log10(up$P_value_adjust), col=1, bg = brewer.pal(9, "YlOrRd")[6], pch=21, cex=1.5)
points(down$fd, -log10(down$P_value_adjust), col = 1, bg = brewer.pal(11,"RdBu")[9], pch = 21,cex=1.5)
  text(up$fd, -log10(up$P_value_adjust),row.names(up),cex=0.5)
  text(down$fd, -log10(down$P_value_adjust),row.names(down),cex=0.5)
abline(h=1.3,v=c(-0.25,0.25),lty=2,lwd=1)
dev.off()

```


VOLCANO zx/ jbdz (in other words: severe - nonCOVID19)
```{r}
library(RColorBrewer)
PT_type <- which(label=="PT")
ZX_type <- which(label=="ZX")
jkdz_type <- which(label=="jkdz")
jbdz_type <- which(label=="jbdz")

df7 <- df2[!apply(df2, 1, function(x)(sum(is.na(x[ZX_type]))/length(ZX_type) > 0.8) | sum(is.na(x[jbdz_type]))/length(jbdz_type) > 0.8),]

for (i in 1:nrow(df7)) {
  df7[i,][is.na(df7[i,])] <- min(df7[i,],na.rm = T)
}

df8 <- 2^df7
df8$fd <- apply(df8,1, function(x) log2((mean(x[ZX_type],na.rm = T)/mean(x[jbdz_type],na.rm = T))))
x<-c(0.0,0.0)
df9 <- df7

for(i in 1:nrow(df9)){
    x[i] <- t.test(df9[i,ZX_type],df9[i,jbdz_type], paired = F, var.equal = F)$p.value
}
df8$P_value<-x
df8$P_value_adjust<-p.adjust(df8$P_value, method="BH")

pdf("ZX_jbdz_point.pdf")
df.point <- data.frame(mean=apply(df7[,c(ZX_type,jbdz_type)],1,mean),fc=df8$fd)
up <- subset(df.point, df.point$mean >23 & df.point$fc > 0.25)
down <- subset(df.point, df.point$mean <16 & df.point$fc < -0.25)
write.csv(rbind(up,down),file = "ZX_jbdz_point.csv")
plot(df.point$mean,df.point$fc)
abline(h=c(-0.25,0.25),lty=2,lwd=1)
  text(up$mean, up$fc,row.names(up),cex=0.5)
  text(down$mean, down$fc,row.names(down),cex=0.5)
dev.off()
pdf("ZX_jbdz_labelpoint.pdf")
df.point <- data.frame(mean=apply(df7[,c(ZX_type,jbdz_type)],1,mean),fc=df8$fd)
plot(df.point$mean,df.point$fc)
abline(h=c(-0.25,0.25),lty=2,lwd=1)
dev.off()


pdf("ZX_jbdz_volcano.pdf")
plot(df8$fd, -log10(df8$P_value_adjust), col="#00000033", pch=19,
      xlab=paste("log2 (fold change)"),
      ylab="-log10 (P_value)",xlim=c(-4,4),
      main="ZX / jbdz")

up <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd > 0.25)
down <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd < -0.25)
write.csv(up,file = "ZX_jbdz_up_volcano.csv")
write.csv(down,file = "ZX_jbdz_dw_volcano.csv")
points(up$fd, -log10(up$P_value_adjust), col=1, bg = brewer.pal(9, "YlOrRd")[6], pch=21, cex=1.5)
points(down$fd, -log10(down$P_value_adjust), col = 1, bg = brewer.pal(11,"RdBu")[9], pch = 21,cex=1.5)
abline(h=1.3,v=c(-0.25,0.25),lty=2,lwd=1)
dev.off()

pdf("ZX_jbdz_labelvolcano.pdf")
plot(df8$fd, -log10(df8$P_value_adjust), col="#00000033", pch=19,
      xlab=paste("log2 (fold change)"),
      ylab="-log10 (P_value)",xlim=c(-4,4),
      main="ZX / jbdz")

up <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd > 0.25)
down <- subset(df8, df8$P_value_adjust < 0.05 & df8$fd < -0.25)
points(up$fd, -log10(up$P_value_adjust), col=1, bg = brewer.pal(9, "YlOrRd")[6], pch=21, cex=1.5)
points(down$fd, -log10(down$P_value_adjust), col = 1, bg = brewer.pal(11,"RdBu")[9], pch = 21,cex=1.5)
  text(up$fd, -log10(up$P_value_adjust),row.names(up),cex=0.5)
  text(down$fd, -log10(down$P_value_adjust),row.names(down),cex=0.5)
abline(h=1.3,v=c(-0.25,0.25),lty=2,lwd=1)
dev.off()

```


all metabonomics feature (add label)
```{r}
plot.pca <- function(data,type,label,title=""){
  library(ggbiplot)
  df10 <- data
  names <-type
  df10 <- t(apply(df10, 1, scale))
  colnames(df10) <- names
  df.pr <- prcomp(t(df10))
  a<- ggbiplot(df.pr, obs.scale = 1, var.scale = 10, groups =names,alpha = 0,varname.size= 1, ellipse =F, circle = F,var.axes = F)+
    geom_point(aes(colour=names),size = 3,alpha=0.8)+
    # geom_point(aes(shape=df1$column),size = 3,alpha=1/2)+
    scale_color_manual(name="type",values=c("#e17832","#537e35","#5992c6","#282f89","#A52A2A"))+
    theme(legend.direction = 'horizontal',legend.position = 'top',legend.text = element_text(size = 15,color = "black"), legend.title = element_text(size=15,color="black") ,panel.grid.major =element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(),axis.line = element_line(colour = "black"))+ theme(panel.grid =element_blank())+
    theme(axis.text = element_text(size = 15,color = "black"))+
    theme(plot.subtitle=element_text(size=30, hjust=0, color="black"))+
    theme(axis.title.x=element_text(size=17, hjust=0.5, color="black"))+
    theme(axis.title.y=element_text(size=17, hjust=0.5, color="black"))  +   geom_text(aes(label=label,vjust = -0.8, hjust = 0.5,size=0.1),show.legend = FALSE)
  ggsave(paste0(title,"_pca.pdf"),plot =a ,device = NULL)
}


df3.meta <- df2[!apply(df2, 1, function(x){sum(is.na(x[zx_type]))/length(zx_type) > 0.8 | sum(is.na(x[pt_type]))/length(pt_type) > 0.8 | sum(is.na(x[jbdz_type]))/length(jbdz_type) > 0.8 | sum(is.na(x[jkbz_type]))/length(jkbz_type) > 0.8}),]

for (i in 1:nrow(df3.meta)) {
  df3.meta[i,][is.na(df3.meta[i,])] <- min(df3.meta[i,],na.rm = T)
}

plot.pca(df3.meta,label,names(df3.meta),"allprot_label")
```



boxplot
```{r}
df7 <- df2
for (i in 1:nrow(df7)) {
  df7[i,][is.na(df7[i,])] <- min(df7[i,],na.rm = T)
}
prot1 <- read.csv("weigang_mata_boxplot.csv")
prot2 <- as.character(prot1$meta)
label <- gsub("\\d+","",names(df2))
df4 <- df7[c(which(row.names(df7) %in% prot2)),label!="NA"]
label4 <- gsub("\\d+","",names(df4))
df.nor <- t(apply(df4, 1, scale)) 
lav <- unique(label4)


for (i in 1:nrow(df.nor)) {
  nm <- row.names(df.nor)[i]
  pv <- c()
  data1 <- data.frame(value=as.numeric(df.nor[i,]),type=label4)
  a1 <- 0
  b1 <- 0
    for (a in lav) {
    for (b in lav) {
        if(a>=b){
          next
        }else{
        a_type <- which(label4 %in% a)
        b_type <- which(label4 %in% b)
        c <- t.test(df.nor[i,a_type],df.nor[i,b_type], paired = F, var.equal = F)$p.value
        pv <- paste0(pv,"\n",a,"_",b,":",format(c,digits = 3, scientific = FALSE))
        }
      b1=b1+1
    }
      a1=a1+1
  }
  
  plot.boxplot <- function(data,x,y,type,filename,title="boxplot"){
  a <- ggplot(data=data, aes(x =x, y =y ,color=type,group=type)) +
    geom_jitter(alpha = 0.3,size=3) +
    geom_boxplot(alpha = .5,size=1)+
    labs(x="sample",y="value",fill= "type")+
    ggtitle(title)+
    theme_bw() + 
    theme(panel.border = element_blank())+
    theme(axis.line = element_line(size=1, colour = "black")) +
    theme(panel.grid =element_blank())+  
    theme(axis.text = element_text(size = 15,colour = "black"),text = element_text(size = 15,colour = "black"))+
    theme(axis.text.x = element_text( hjust = 1,angle = 45))+
    scale_x_discrete(limit=c("jkdz","jbdz","PT","ZX") )+
    scale_color_manual(limits=c("jkdz","jbdz","PT","ZX"), values=c("#85B22E","#5F80B4","#E29827","#922927"))
  ggsave(paste0(filename, ".pdf"),plot=a,width=8,height=8)
}
  plot.boxplot( data1,data1$type,data1$value,data1$type,paste0("meta16_boxplot/meta",i, "_boxplot"),title=paste0(nm, pv))
}



which(grepl("choline",row.names(df2) ))

```
